# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_user_date_hired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishcopier_id', models.ManyToManyField(related_name='wishcopier', to='login.User')),
                ('wishmaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishmaker', to='login.User')),
            ],
            managers=[
                ('wishlistManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
