# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 17, 0, 40, 725972, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
